### ISSUE TITLE
Peer to peer code review by team 125 The Elmos

### ISSUE THREAD

**Issue by ershadul1** [Joseph-Burke/The-Next-Web#3]
There are things that I can work on to improve the project.

- I need to add links to the page instead of just embedded images and texts
- The code will be cleaner if I use variables for repetitive colors
- CSS will be more beautiful if I use more general classes. e.g classes for- display flex
- The contribution section in the README.MD needs to be more descriptive
- The stylelint.json file should not be ignored. The GitHub actions will work faster if this file is in the repo.

**Comment by descholar-ceo** [comment]
You did a good job @ershadul1 && @Joseph-Burke, keep up the good work
